### PR TITLE
fix/stay-updated-link

### PR DESCRIPTION
**Pull request by pjosh**
## Overview

BC thread: https://basecamp.com/3063126/projects/10728552/todos/333058272

### CODE REVIEW

**Review by edbrett — COMMENTED** [review]
I think this still makes the page reload?

**Comment by pjosh** [comment]
yeah of course, but in your current landing, not to the home page.
But, I know what you mean... It's better to change the behaviour and show the popup on click. I'm going to do that! thanks!

**Comment by pjosh** [comment]
@edbrett done!

**Review by edbrett — APPROVED** [review]
The hero we need 👏

**Pull request merged**
